/**
 * Curated list of French private foundations that fund associations/NGOs.
 *
 * This is the single source of truth used by the TypeScript ingestion runner
 * (src/lib/ingestion/index.ts → SOURCES → "Fondations françaises (curated)").
 * We also mirror the same list in scripts/ingest-fondations.mjs so the
 * standalone Node script can run without a TS pipeline.
 *
 * Data quality notes:
 *  - Every entry has the direct URL of the foundation so the "Contacter la
 *    fondation" CTA on the matching page and the grant detail page can deep
 *    link to the right page (often an "appels à projets" landing page).
 *  - `maxAmount` is an ORDER-OF-MAGNITUDE estimate based on public reports
 *    or typical bourse/prix — not a guarantee. The matching engine uses it
 *    to size the opportunity vs. project budget, so rough is fine.
 *  - Themes align with the 12 canonical thematic areas used elsewhere in the
 *    app (Humanitaire, Éducation, Jeunesse, Inclusion, Culture, Santé,
 *    Environnement, Droits humains, Migration, Développement, Égalité,
 *    Numérique). Free-form additions are welcome — the matcher treats
 *    unknown themes as soft signals.
 *
 * Updated: 2026-04 (130+ foundations, deduplicated by URL).
 */

interface CuratedFoundation {
  name: string;
  themes: string[];
  url: string;
  summary: string;
  maxAmount: number;
}

const FONDATIONS: CuratedFoundation[] = [
  // ─── FONDATIONS GÉNÉRALISTES / RUP PHARES ─────────────────────────
  {
    name: "Fondation de France",
    themes: ["Solidarité", "Environnement", "Culture", "Éducation", "Recherche", "Santé"],
    url: "https://www.fondationdefrance.org/fr/appels-a-projets",
    summary: "1ère fondation française. Appels à projets dans tous les domaines de l'intérêt général. 3 000+ projets soutenus/an, abrite 900 fondations sous égide.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Abbé Pierre",
    themes: ["Logement", "Précarité", "Exclusion", "Humanitaire"],
    url: "https://www.fondation-abbe-pierre.fr/nous-soutenir/appels-a-projets",
    summary: "Lutte contre le mal-logement et l'exclusion. Finance des projets d'hébergement, d'accès au logement et d'accompagnement social.",
    maxAmount: 200000,
  },
  {
    name: "Fondation Apprentis d'Auteuil",
    themes: ["Jeunesse", "Éducation", "Protection de l'enfance", "Insertion"],
    url: "https://www.apprentis-auteuil.org/",
    summary: "Protection de l'enfance et insertion des jeunes. Programmes éducatifs et d'accompagnement en France et à l'international.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Bettencourt Schueller",
    themes: ["Recherche", "Sciences", "Culture", "Arts", "Solidarité"],
    url: "https://www.fondationbs.org/fr/candidater-pour-un-prix",
    summary: "Fondation majeure (dotation ~5 Md€). Prix annuels et appels dans les sciences, les arts et la solidarité. Dotations jusqu'à 500 000 €.",
    maxAmount: 500000,
  },
  {
    name: "Fondation Daniel et Nina Carasso",
    themes: ["Alimentation durable", "Art citoyen", "Environnement", "Culture"],
    url: "https://www.fondationcarasso.org/appels-a-projets/",
    summary: "Finance des projets innovants en alimentation durable et art citoyen. Appels à projets récurrents en France et en Espagne.",
    maxAmount: 150000,
  },
  {
    name: "Fondation Caritas France",
    themes: ["Solidarité", "Pauvreté", "Exclusion", "Migration"],
    url: "https://www.fondation-caritas.org/nos-appels-a-projets/",
    summary: "Lutte contre la pauvreté et l'exclusion. Finance des projets d'insertion, d'hébergement et d'aide alimentaire en France.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Nicolas Hulot pour la Nature et l'Homme",
    themes: ["Environnement", "Écologie", "Biodiversité", "Transition"],
    url: "https://www.fnh.org/programmes/",
    summary: "Sensibilisation et actions pour la transition écologique. Soutient des projets de préservation de la biodiversité et d'écologie sociale.",
    maxAmount: 30000,
  },
  {
    name: "Fondation La France s'engage",
    themes: ["Innovation sociale", "Solidarité", "Éducation", "Inclusion"],
    url: "https://fondationlafrancesengage.org/nos-lauréats/",
    summary: "Programme de labellisation + accompagnement pluriannuel (jusqu'à 300 k€) pour les innovateurs sociaux à fort impact.",
    maxAmount: 300000,
  },
  {
    name: "Fondation du Patrimoine",
    themes: ["Culture", "Patrimoine", "Territoires"],
    url: "https://www.fondation-patrimoine.org/",
    summary: "Sauvegarde du patrimoine de proximité (bâti, naturel, mobilier). Mécénat, souscriptions publiques, loto du patrimoine.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Roi Baudouin (France)",
    themes: ["Solidarité", "Pauvreté", "Migration", "Justice sociale"],
    url: "https://www.kbs-frb.be/fr",
    summary: "Fondation belge avec programmes en France. Pauvreté, justice sociale, migration, patrimoine.",
    maxAmount: 60000,
  },
  {
    name: "Fondation JM Bruneau",
    themes: ["Précarité", "Santé", "Éducation", "Exclusion"],
    url: "https://www.fondation-bruneau.fr/",
    summary: "Soutient les projets d'aide aux personnes démunies : santé, éducation, insertion. Sous égide de la Fondation de France.",
    maxAmount: 30000,
  },
  {
    name: "Fondation de l'Olivier",
    themes: ["Précarité", "Santé", "Logement"],
    url: "https://www.fondationdelolivier.org/",
    summary: "Santé et précarité. Accès aux soins des personnes en grande exclusion. Sous égide de la Fondation de France.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Avril",
    themes: ["Agriculture", "Alimentation", "Développement rural", "Afrique"],
    url: "https://www.fondationavril.org/nos-appels-a-projets/",
    summary: "Développement agricole et rural en France et en Afrique de l'Ouest. Sécurité alimentaire, structuration des filières.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Artémis (Pinault)",
    themes: ["Culture", "Arts", "Solidarité"],
    url: "https://www.groupe-artemis.com/",
    summary: "Mécénat culturel et artistique, solidarité, éducation. Projets portés par le groupe Artémis (Pinault).",
    maxAmount: 200000,
  },
  {
    name: "Fondation Seligmann",
    themes: ["Laïcité", "Droits humains", "Antiracisme", "Égalité"],
    url: "https://www.fondation-seligmann.org/",
    summary: "Lutte contre les discriminations, promotion de la laïcité et du vivre-ensemble. Soutient les projets associatifs en Île-de-France.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Hirondelle",
    themes: ["Média", "Droits humains", "Développement", "International"],
    url: "https://www.hirondelle.org/fr/",
    summary: "Médias dans les zones de crise pour l'accès à l'information. Projets en Afrique, Asie, zones post-conflit.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Ashoka France",
    themes: ["Innovation sociale", "Entrepreneuriat", "Impact"],
    url: "https://www.ashoka.org/fr-fr",
    summary: "Communauté d'entrepreneurs sociaux (Ashoka Fellows). Accompagnement, réseau et stipend pluriannuel.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Un Monde Par Tous",
    themes: ["Droits humains", "Solidarité internationale", "Démocratie"],
    url: "https://www.fondation-un-monde-par-tous.org/",
    summary: "Droits humains, justice sociale et économique, solidarité internationale. Fondation sous égide de la Fondation Charles Léopold Mayer.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Terre Solidaire",
    themes: ["Environnement", "Transition écologique", "Agriculture paysanne"],
    url: "https://fondation-terresolidaire.org/",
    summary: "Transitions écologique et solidaire : agriculture paysanne, énergie, modèles économiques soutenables.",
    maxAmount: 30000,
  },

  // ─── FONDATIONS D'ENTREPRISE — TELECOM / ÉNERGIE / INDUSTRIE ──────
  {
    name: "Fondation Orange",
    themes: ["Numérique", "Inclusion", "Éducation", "Autisme", "Culture"],
    url: "https://www.fondationorange.com/Presentation-de-nos-appels-a-projets",
    summary: "Inclusion numérique, éducation des femmes, autisme, culture. Appels à projets récurrents + partenariats structurants.",
    maxAmount: 50000,
  },
  {
    name: "Fondation TotalEnergies",
    themes: ["Éducation", "Insertion", "Patrimoine", "Biodiversité", "Climat"],
    url: "https://foundation.totalenergies.com/fr",
    summary: "Éducation, insertion professionnelle, biodiversité marine, patrimoine culturel, dialogue interculturel.",
    maxAmount: 100000,
  },
  {
    name: "Fondation EDF",
    themes: ["Santé", "Inclusion", "Solidarité", "Éducation"],
    url: "https://www.fondation.edf.com/",
    summary: "Solidarité, santé, inclusion, éducation. Soutien aux projets associatifs locaux et nationaux.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Engie",
    themes: ["Précarité énergétique", "Environnement", "Enfance"],
    url: "https://www.fondation-engie.com/appels-a-projets/",
    summary: "Lutte contre la précarité énergétique, accès à l'énergie durable en France et dans les pays émergents.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Air Liquide",
    themes: ["Environnement", "Santé respiratoire", "Éducation scientifique"],
    url: "https://fondationairliquide.com/",
    summary: "Environnement, santé respiratoire, développement des territoires. Fondation active en France et à l'international.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Schneider Electric",
    themes: ["Énergie", "Formation", "Insertion", "Développement"],
    url: "https://www.se.com/fr/fr/about-us/sustainability/foundation/",
    summary: "Formation aux métiers de l'énergie et insertion professionnelle des jeunes. Active en France et pays en développement.",
    maxAmount: 60000,
  },
  {
    name: "Fondation Veolia",
    themes: ["Environnement", "Eau", "Déchets", "Urgence humanitaire"],
    url: "https://www.fondation.veolia.com/fr/appels-projets",
    summary: "Projets environnementaux, urgence humanitaire, emploi solidaire. Mobilise le mécénat de compétences des salariés.",
    maxAmount: 75000,
  },
  {
    name: "Fondation Michelin",
    themes: ["Mobilité", "Environnement", "Sport", "Santé", "Éducation"],
    url: "https://www.fondation.michelin.com/fr/",
    summary: "Mobilité durable, santé, sport, éducation. Projets internationaux et dans les territoires Michelin.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Vicat",
    themes: ["Territoires", "Solidarité", "Éducation", "Environnement"],
    url: "https://www.vicat.fr/notre-groupe/fondation-vicat",
    summary: "Fondation d'entreprise du cimentier Vicat. Soutient les associations dans les territoires où le groupe est implanté.",
    maxAmount: 25000,
  },
  {
    name: "Fondation SAFRAN",
    themes: ["Éducation", "Insertion", "Jeunesse", "Sciences"],
    url: "https://www.safran-group.com/fr/groupe/fondation-safran",
    summary: "Éducation des jeunes défavorisés, sciences, égalité des chances. Fondation d'entreprise du groupe Safran.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Thales Solidarité",
    themes: ["Insertion", "Éducation", "Handicap"],
    url: "https://www.thalesgroup.com/fr/monde/foundation",
    summary: "Insertion professionnelle, éducation et inclusion des personnes handicapées. Projets soutenus par les salariés Thales.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Alstom",
    themes: ["Mobilité durable", "Insertion", "Éducation"],
    url: "https://www.alstom.com/fr/groupe/la-fondation-alstom",
    summary: "Mobilité durable, insertion, éducation aux métiers techniques. Projets locaux portés par les salariés.",
    maxAmount: 10000,
  },
  {
    name: "Fondation RTE",
    themes: ["Territoires ruraux", "Lien social", "Énergie", "Mobilité"],
    url: "https://www.fondation-rte.org/appel-a-projets/",
    summary: "Cohésion des territoires ruraux. Appels à projets annuels pour associations en zones rurales.",
    maxAmount: 40000,
  },
  {
    name: "Fondation GRDF",
    themes: ["Précarité énergétique", "Lien social"],
    url: "https://www.grdf.fr/institutionnel/grdf/fondation-grdf",
    summary: "Lutte contre la précarité énergétique, cohésion sociale dans les territoires.",
    maxAmount: 20000,
  },

  // ─── FONDATIONS D'ENTREPRISE — TRANSPORT / MOBILITÉ ───────────────
  {
    name: "Fondation SNCF",
    themes: ["Éducation", "Insertion", "Illettrisme", "Lien social"],
    url: "https://www.fondation-sncf.org/fr/appels-a-projets/",
    summary: "Éducation des jeunes, prévention de l'illettrisme, lien social dans les territoires. Appels à projets annuels.",
    maxAmount: 50000,
  },
  {
    name: "Fondation RATP",
    themes: ["Insertion", "Éducation", "Lien social", "Inclusion"],
    url: "https://www.fondationratp.fr/appels-a-projets",
    summary: "Insertion et lutte contre la fracture sociale dans les territoires urbains. Mécénat de compétences RATP.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Vinci pour la Cité",
    themes: ["Insertion", "Emploi", "Mobilité", "Logement"],
    url: "https://www.fondation-vinci.com/",
    summary: "Insertion professionnelle, mobilité, accès au logement. Appels à projets locaux via salariés parrains.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Groupe ADP",
    themes: ["Insertion", "Éducation", "Environnement", "Territoires aéroportuaires"],
    url: "https://www.parisaeroport.fr/groupe/engagements/fondation-groupe-adp",
    summary: "Insertion, éducation, environnement dans les territoires autour des aéroports parisiens.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Transdev",
    themes: ["Mobilité", "Insertion", "Territoires"],
    url: "https://www.transdev.com/fr/groupe/fondation/",
    summary: "Mobilité solidaire et inclusive. Projets d'accès à la mobilité pour les publics fragiles.",
    maxAmount: 20000,
  },
  {
    name: "Fondation CMA CGM",
    themes: ["Enfance", "Éducation", "Humanitaire maritime"],
    url: "https://www.cmacgm-foundation.org/fr/",
    summary: "Enfance, éducation, urgences humanitaires et solidarité maritime. Active en France et à l'international.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Renault",
    themes: ["Éducation", "Mobilité", "Recherche"],
    url: "https://group.renault.com/groupe/engagements/la-fondation-renault/",
    summary: "Éducation, recherche et mobilité durable. Chaires universitaires et projets avec des grandes écoles.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Stellantis",
    themes: ["Insertion", "Éducation", "Mobilité"],
    url: "https://www.stellantis.com/fr/groupe/fondation",
    summary: "Insertion, éducation, mobilité dans les territoires d'implantation Stellantis (ex-PSA + FCA).",
    maxAmount: 30000,
  },

  // ─── FONDATIONS D'ENTREPRISE — BANQUE / ASSURANCE ─────────────────
  {
    name: "Fondation BNP Paribas",
    themes: ["Culture", "Solidarité", "Recherche médicale", "Environnement"],
    url: "https://fondation.bnpparibas/fr/nos-appels-a-projets/",
    summary: "Culture, recherche médicale, changement climatique, insertion. Appels à projets structurants avec financements pluriannuels.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Société Générale",
    themes: ["Insertion", "Éducation", "Sport", "Culture"],
    url: "https://www.fondation-societegenerale.com/appels-a-projets/",
    summary: "Insertion professionnelle et éducation via la pratique sportive et culturelle.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Crédit Agricole — Pays de France",
    themes: ["Patrimoine", "Insertion", "Territoires", "Culture"],
    url: "https://fondation-ca-paysdefrance.org/",
    summary: "Projets d'intérêt général portés par les associations en région (patrimoine, insertion, culture rurale).",
    maxAmount: 40000,
  },
  {
    name: "Fondation Crédit Agricole Solidarité et Développement",
    themes: ["Solidarité", "Précarité", "Insertion"],
    url: "https://www.credit-agricole.com/engagements/fondations/fondation-credit-agricole-solidarite-et-developpement",
    summary: "Lutte contre la pauvreté et l'exclusion. Partenariats avec les caisses régionales du Crédit Agricole.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Crédit Coopératif",
    themes: ["Économie sociale", "Innovation sociale", "Solidarité"],
    url: "https://www.credit-cooperatif.coop/fondation",
    summary: "Innovation dans l'économie sociale et solidaire. Prix et bourses pour les structures ESS.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Caisse d'Épargne pour la solidarité",
    themes: ["Autonomie", "Dépendance", "Aidants", "Inclusion"],
    url: "https://www.fondation-caisse-epargne.fr/appels-a-projets/",
    summary: "Lutte contre la dépendance, soutien aux aidants, inclusion des personnes âgées et handicapées.",
    maxAmount: 40000,
  },
  {
    name: "Fondation d'entreprise Banque Populaire",
    themes: ["Handicap", "Musique", "Artisanat d'art"],
    url: "https://www.fondation.banquepopulaire.fr/",
    summary: "Bourses et prix pour personnes handicapées, musiciens classiques, artisans d'art.",
    maxAmount: 25000,
  },
  {
    name: "Fondation CASDEN Banque Populaire",
    themes: ["Éducation", "Éducation populaire", "Territoires"],
    url: "https://www.casden.fr/la-fondation-casden",
    summary: "Éducation, coopération, valeurs de l'éducation populaire. Soutient les associations d'enseignants et d'éducation.",
    maxAmount: 15000,
  },
  {
    name: "Fondation AXA",
    themes: ["Recherche", "Risques", "Santé", "Environnement"],
    url: "https://www.axa-research.org/fr",
    summary: "Recherche académique sur les risques (santé, climat, société). Bourses post-doc et chaires.",
    maxAmount: 150000,
  },
  {
    name: "Fondation AG2R La Mondiale",
    themes: ["Autonomie", "Lien social", "Santé", "Prévention"],
    url: "https://www.ag2rlamondiale.fr/vivons-ensemble/notre-engagement/nos-fondations",
    summary: "Prévention santé, autonomie des personnes âgées, lien intergénérationnel, vivre ensemble.",
    maxAmount: 50000,
  },
  {
    name: "Fondation MACIF",
    themes: ["Économie sociale", "Innovation sociale", "Inclusion", "Santé"],
    url: "https://www.fondation-macif.org/appels-a-projets/",
    summary: "Économie sociale et solidaire, innovation sociale, santé, éducation. Ancrage régional fort.",
    maxAmount: 50000,
  },
  {
    name: "Fondation MAIF",
    themes: ["Prévention", "Risques", "Mobilité", "Recherche"],
    url: "https://www.fondation-maif.fr/appels-a-projets.html",
    summary: "Prévention des risques du quotidien (mobilité, domicile, numérique). Bourses de recherche appliquée.",
    maxAmount: 60000,
  },
  {
    name: "Fondation Groupama",
    themes: ["Santé", "Maladies rares", "Ruralité"],
    url: "https://www.fondation-groupama.com/",
    summary: "Santé et maladies rares, soutien aux malades et à leurs aidants, projets en milieu rural.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Allianz — Un Avenir Ensemble",
    themes: ["Jeunesse", "Mérite", "Insertion"],
    url: "https://www.allianz.fr/qui-sommes-nous/fondation-allianz.html",
    summary: "Bourses pour jeunes méritants issus de milieux modestes. Accompagnement jusqu'à l'insertion professionnelle.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Malakoff Humanis Handicap",
    themes: ["Handicap", "Insertion", "Sport adapté"],
    url: "https://www.malakoffhumanis.com/fondation-handicap/",
    summary: "Handicap et insertion : emploi, sport adapté, autonomie, recherche. Dotation ~5 M€/an.",
    maxAmount: 60000,
  },
  {
    name: "Fondation Klesia",
    themes: ["Handicap", "Autonomie", "Aidants"],
    url: "https://www.klesia.fr/fondation",
    summary: "Handicap, autonomie, fragilités de la vie. Soutien aux associations et à la recherche.",
    maxAmount: 40000,
  },

  // ─── FONDATIONS D'ENTREPRISE — DISTRIBUTION / ALIMENTATION ────────
  {
    name: "Fondation Carrefour",
    themes: ["Alimentation", "Précarité alimentaire", "Urgence humanitaire"],
    url: "https://www.fondation-carrefour.org/fr/appel-a-projets/",
    summary: "Lutte contre la précarité alimentaire, transition alimentaire, urgence humanitaire. Projets en France et à l'international.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Auchan pour la jeunesse",
    themes: ["Jeunesse", "Éducation", "Alimentation", "Lien social"],
    url: "https://www.auchan-retail.com/fr/foundation-auchan/",
    summary: "Jeunesse, éducation au bien manger, lien social. Appels à projets portés par les salariés dans les magasins.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Monoprix",
    themes: ["Urbain", "Solidarité", "Lien social"],
    url: "https://www.monoprix.fr/notre-entreprise/nos-engagements/fondation-monoprix",
    summary: "Vie en ville, solidarité urbaine, lien social dans les quartiers.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Leclerc",
    themes: ["Culture", "Éducation", "Cinéma"],
    url: "https://www.mecenat-e-leclerc.com/",
    summary: "Mécénat culturel E.Leclerc : livre, cinéma, photographie. Soutien aux projets d'accès à la culture.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Lidl",
    themes: ["Alimentation", "Précarité", "Environnement"],
    url: "https://fondation.lidl.fr/",
    summary: "Lutte contre la précarité alimentaire, gaspillage, nutrition. Appels à projets associations anti-gaspi.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Bel",
    themes: ["Enfance", "Alimentation", "Éducation"],
    url: "https://www.groupe-bel.com/fr/engagements/fondation-bel/",
    summary: "Alimentation des enfants, éducation au goût. Projets en France et dans les pays d'implantation.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Nestlé France",
    themes: ["Nutrition", "Enfance", "Précarité alimentaire"],
    url: "https://www.nestle.fr/csv/engagements-societaux/fondation-nestle-france",
    summary: "Nutrition, santé infantile, lutte contre la précarité alimentaire.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Ronald McDonald",
    themes: ["Santé", "Enfance", "Hébergement des familles"],
    url: "https://www.fondation-ronald-mcdonald.fr/",
    summary: "Maisons d'accueil pour familles d'enfants hospitalisés. Soutien aux associations santé-enfance.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Danone Communities",
    themes: ["Alimentation", "Nutrition", "Développement"],
    url: "https://www.danonecommunities.com/fr/",
    summary: "Entreprises sociales pour l'accès à l'eau et à la nutrition dans les pays en développement.",
    maxAmount: 100000,
  },

  // ─── FONDATIONS D'ENTREPRISE — LUXE / MODE / COSMÉTIQUE ───────────
  {
    name: "Fondation L'Oréal",
    themes: ["Femmes", "Sciences", "Beauté", "Vulnérabilité"],
    url: "https://www.fondationloreal.com/",
    summary: "Femmes et sciences (prix L'Oréal-UNESCO), beauté pour tous, femmes vulnérables. Dotation importante.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Kering",
    themes: ["Droits des femmes", "Violences", "Égalité"],
    url: "https://www.keringfoundation.org/fr/",
    summary: "Lutte contre les violences faites aux femmes. Finance les associations de terrain et la prévention.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Hermès",
    themes: ["Culture", "Artisanat", "Savoir-faire", "Biodiversité"],
    url: "https://www.fondationdentreprisehermes.org/fr/appels-a-projets",
    summary: "Savoir-faire artisanal, création contemporaine, biodiversité, solidarité. Appels à projets structurants.",
    maxAmount: 60000,
  },
  {
    name: "Fondation Chanel",
    themes: ["Femmes", "Égalité", "Autonomie économique"],
    url: "https://www.fondationchanel.org/fr/",
    summary: "Autonomie économique et sociale des femmes. Programmes pluriannuels avec des associations partenaires.",
    maxAmount: 200000,
  },
  {
    name: "Fondation Louis Vuitton",
    themes: ["Culture", "Arts contemporains", "Musique"],
    url: "https://www.fondationlouisvuitton.fr/",
    summary: "Mécénat culturel (art contemporain, musique, éducation). Programmes scolaires et partenariats artistiques.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Cartier pour l'art contemporain",
    themes: ["Culture", "Arts contemporains"],
    url: "https://www.fondationcartier.com/",
    summary: "Art contemporain : expositions, résidences, acquisitions. Soutient les artistes et les associations culturelles.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Galeries Lafayette",
    themes: ["Culture", "Création contemporaine", "Mode"],
    url: "https://www.fondationgalerieslafayette.com/",
    summary: "Création contemporaine émergente : arts visuels, mode, design. Résidences et expositions.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Louis Roederer",
    themes: ["Culture", "Patrimoine", "Photographie"],
    url: "https://www.louis-roederer.com/fr/fondation",
    summary: "Mécénat culturel : photographie, patrimoine, livre ancien, musique classique.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Lagardère",
    themes: ["Jeunesse", "Culture", "Média", "Livre"],
    url: "https://www.fondation-jeanluclagardere.com/",
    summary: "Bourses pour jeunes talents : journalisme, édition, cinéma, libraires, musique, numérique.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Mustela",
    themes: ["Enfance", "Maternité", "Éducation parentale"],
    url: "https://www.fondation-mustela.com/appels-a-projets",
    summary: "Enfance et parentalité : soutien à la recherche et aux associations d'accompagnement des jeunes enfants.",
    maxAmount: 15000,
  },

  // ─── FONDATIONS D'ENTREPRISE — TECH / NUMÉRIQUE / SERVICES ────────
  {
    name: "Fondation Bouygues Telecom",
    themes: ["Culture", "Patrimoine", "Numérique", "Solidarité"],
    url: "https://www.fondationbouyguestelecom.fr/appels-a-projets/",
    summary: "Coup de pouce aux projets associatifs locaux, patrimoine, livres, solidarité numérique.",
    maxAmount: 10000,
  },
  {
    name: "Fondation Afnic pour la solidarité numérique",
    themes: ["Numérique", "Inclusion", "Territoires"],
    url: "https://www.fondation-afnic.fr/fr/appels-a-projets/",
    summary: "Solidarité numérique et accès au digital pour les publics éloignés. Appels à projets annuels.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Accenture France",
    themes: ["Insertion", "Emploi", "Compétences", "Inclusion numérique"],
    url: "https://www.accenture.com/fr-fr/about/corporate-citizenship-index",
    summary: "Insertion professionnelle, compétences numériques, mentorat des jeunes en difficulté.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Microsoft France",
    themes: ["Numérique", "Éducation", "Inclusion"],
    url: "https://www.microsoft.com/fr-fr/corporate-responsibility",
    summary: "Compétences numériques, inclusion, ONG. Mécénat technologique (Azure credits) + financement.",
    maxAmount: 40000,
  },
  {
    name: "Fondation d'entreprise Up (Chèque Déjeuner)",
    themes: ["Économie sociale", "Solidarité", "Alimentation"],
    url: "https://www.up.coop/fondation",
    summary: "Économie sociale et solidaire, alimentation durable, accès à la culture et aux loisirs.",
    maxAmount: 25000,
  },
  {
    name: "Fondation La Poste",
    themes: ["Culture", "Écriture", "Lien social"],
    url: "https://www.fondationlaposte.org/",
    summary: "Expression écrite, lettres et lecture, lien social par le courrier.",
    maxAmount: 20000,
  },
  {
    name: "Fondation d'entreprise FDJ",
    themes: ["Insertion", "Sport", "Culture"],
    url: "https://www.fdj.fr/groupe/engagements/fondation",
    summary: "Insertion par le sport, lutte contre l'illettrisme, engagement des jeunes.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Nexity",
    themes: ["Logement", "Ville", "Inclusion"],
    url: "https://fondation.nexity.fr/",
    summary: "Logement des publics fragiles, ville inclusive, accompagnement social.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Optic 2000",
    themes: ["Santé visuelle", "Accessibilité", "Aidants"],
    url: "https://www.optic2000.com/fondation",
    summary: "Santé visuelle, accessibilité, soutien aux aidants. Dons matériels + financement.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Decathlon",
    themes: ["Sport", "Inclusion", "Handicap", "Santé"],
    url: "https://fondation.decathlon.com/",
    summary: "Accès au sport pour les personnes éloignées de la pratique (handicap, précarité, quartiers prioritaires).",
    maxAmount: 30000,
  },

  // ─── SANTÉ / RECHERCHE MÉDICALE ───────────────────────────────────
  {
    name: "Fondation pour la Recherche Médicale (FRM)",
    themes: ["Recherche", "Santé", "Sciences de la vie"],
    url: "https://www.frm.org/nos-appels-a-projets",
    summary: "Financement de la recherche médicale française. Bourses et équipes de recherche, tous champs de la santé.",
    maxAmount: 350000,
  },
  {
    name: "Fondation ARC pour la recherche sur le cancer",
    themes: ["Recherche", "Cancer", "Santé"],
    url: "https://www.fondation-arc.org/appels-a-projets",
    summary: "Recherche sur le cancer. Programmes, bourses doctorales/post-doc, soutien aux équipes labellisées.",
    maxAmount: 300000,
  },
  {
    name: "Fondation de l'Avenir",
    themes: ["Recherche médicale", "Innovation", "Soins"],
    url: "https://www.fondationdelavenir.org/",
    summary: "Recherche médicale appliquée et innovation en santé. Spécialisée sur la recherche mutualiste.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Institut Pasteur",
    themes: ["Recherche", "Santé", "Maladies infectieuses"],
    url: "https://www.pasteur.fr/fr/institut-pasteur/soutenir-l-institut-pasteur",
    summary: "Recherche biomédicale : maladies infectieuses, vaccins, résistances. Partenariats avec ONG santé internationale.",
    maxAmount: 200000,
  },
  {
    name: "Fondation Institut Curie",
    themes: ["Recherche", "Cancer", "Oncologie"],
    url: "https://curie.fr/fondation",
    summary: "Recherche et soins en cancérologie. Bourses et partenariats associatifs.",
    maxAmount: 150000,
  },
  {
    name: "Fondation Gustave Roussy",
    themes: ["Cancer", "Recherche", "Patients"],
    url: "https://www.gustaveroussy.fr/fr/fondation-gustave-roussy",
    summary: "Recherche en oncologie et soutien aux patients de l'IGR.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Hôpitaux de Paris-Hôpitaux de France",
    themes: ["Santé", "Hôpital", "Enfants", "Personnes âgées"],
    url: "https://www.fondationhopitaux.fr/",
    summary: "Amélioration du quotidien à l'hôpital pour enfants et personnes âgées. Opération Pièces Jaunes.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Médéric Alzheimer",
    themes: ["Alzheimer", "Personnes âgées", "Aidants"],
    url: "https://www.fondation-mederic-alzheimer.org/nos-appels-a-projets",
    summary: "Recherche et projets de terrain sur la maladie d'Alzheimer et les maladies apparentées.",
    maxAmount: 50000,
  },
  {
    name: "Fondation France Alzheimer",
    themes: ["Alzheimer", "Aidants", "Formation"],
    url: "https://www.francealzheimer.org/",
    summary: "Soutien aux familles, formation des aidants, recherche. Financement d'initiatives associatives locales.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Maladies Rares",
    themes: ["Maladies rares", "Recherche", "Patients"],
    url: "https://fondation-maladiesrares.org/appels-a-projets/",
    summary: "Recherche sur les maladies rares, accompagnement des patients, coopération européenne.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Française pour la Recherche sur le Diabète",
    themes: ["Diabète", "Recherche", "Santé"],
    url: "https://www.frdiabete.org/",
    summary: "Recherche clinique et fondamentale sur le diabète.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Cœur et Recherche",
    themes: ["Cardiologie", "Recherche", "Santé"],
    url: "https://www.coeur-recherche.fr/",
    summary: "Recherche cardiovasculaire. Bourses et soutien aux équipes de recherche clinique.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Mérieux",
    themes: ["Santé", "Maladies infectieuses", "Pays en développement"],
    url: "https://www.fondation-merieux.org/",
    summary: "Santé publique et maladies infectieuses dans les pays à faible revenu. Diagnostic et renforcement des laboratoires.",
    maxAmount: 150000,
  },
  {
    name: "Fondation Pierre Fabre",
    themes: ["Santé", "Pays en développement", "Médicaments"],
    url: "https://www.fondationpierrefabre.org/",
    summary: "Accès aux médicaments et aux soins dans les pays du Sud. Drépanocytose, santé mère-enfant, dermatologie.",
    maxAmount: 200000,
  },
  {
    name: "Fondation Raoul Follereau",
    themes: ["Lèpre", "Pauvreté", "Afrique"],
    url: "https://www.raoul-follereau.org/",
    summary: "Lutte contre la lèpre, la pauvreté et l'exclusion. Programmes en Afrique et en France.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Sanofi Espoir",
    themes: ["Santé", "Pauvreté infantile", "International"],
    url: "https://www.fondation-sanofi-espoir.com/appels-a-projets.php",
    summary: "Santé des mères et enfants dans les zones fragiles, lutte contre les cancers pédiatriques.",
    maxAmount: 100000,
  },

  // ─── HANDICAP / INCLUSION ─────────────────────────────────────────
  {
    name: "Fondation Perce-Neige",
    themes: ["Handicap mental", "Autisme", "Hébergement"],
    url: "https://www.perce-neige.org/",
    summary: "Handicap mental et psychique. Hébergement, accompagnement, soutien aux familles.",
    maxAmount: 50000,
  },
  {
    name: "Fondation APAJH",
    themes: ["Handicap", "Inclusion", "Éducation"],
    url: "https://www.apajh.org/",
    summary: "Inclusion et citoyenneté des personnes en situation de handicap. Établissements + plaidoyer.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Paul Bennetot",
    themes: ["Handicap", "Aidants", "Autonomie"],
    url: "https://www.fondation-paulbennetot.org/",
    summary: "Handicap, autonomie, aidants familiaux. Sous égide de la Fondation de l'Avenir.",
    maxAmount: 30000,
  },
  {
    name: "Fondation OVE",
    themes: ["Handicap", "Inclusion", "Éducation spécialisée"],
    url: "https://www.fondation-ove.fr/",
    summary: "Accompagnement et scolarisation des enfants et adultes en situation de handicap.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Falret",
    themes: ["Santé mentale", "Handicap psychique", "Inclusion"],
    url: "https://www.falret.org/",
    summary: "Santé mentale et handicap psychique. Accompagnement, logement, emploi adapté.",
    maxAmount: 30000,
  },
  {
    name: "Fondation OCH (Office Chrétien des personnes Handicapées)",
    themes: ["Handicap", "Familles", "Spiritualité"],
    url: "https://www.och.fr/",
    summary: "Soutien aux personnes handicapées et à leurs familles. Formation, écoute, accompagnement.",
    maxAmount: 20000,
  },

  // ─── ENVIRONNEMENT / BIODIVERSITÉ / CLIMAT ────────────────────────
  {
    name: "Fondation Yves Rocher",
    themes: ["Environnement", "Biodiversité", "Femmes en environnement"],
    url: "https://www.fondationyvesrocher.org/fr/",
    summary: "Plantation d'arbres, prix Terre de Femmes (femmes engagées pour la nature), projets associatifs.",
    maxAmount: 30000,
  },
  {
    name: "Fondation GoodPlanet",
    themes: ["Environnement", "Éducation à l'écologie", "Climat"],
    url: "https://www.goodplanet.org/fr/",
    summary: "Éducation à l'écologie, sensibilisation climat, projets à impact (Yann Arthus-Bertrand).",
    maxAmount: 25000,
  },
  {
    name: "Fondation Tara Océan",
    themes: ["Océan", "Biodiversité marine", "Recherche"],
    url: "https://fondationtaraocean.org/",
    summary: "Science et sensibilisation sur l'océan et le climat. Partenariats scientifiques et éducatifs.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Léa Nature / Jardin Bio",
    themes: ["Environnement", "Bio", "Biodiversité", "Santé environnementale"],
    url: "https://www.groupe-lea-nature.fr/fondation-lea-nature-jardin-bio",
    summary: "Écologie, santé environnementale, agriculture bio. 1% pour la planète (plus de 350 assos soutenues/an).",
    maxAmount: 20000,
  },
  {
    name: "Fondation Nature & Découvertes",
    themes: ["Biodiversité", "Éducation à la nature"],
    url: "https://www.natureetdecouvertes.com/ecologie/fondation",
    summary: "Protection de la biodiversité, éducation à la nature, projets ruraux de préservation.",
    maxAmount: 10000,
  },
  {
    name: "Fondation Ensemble",
    themes: ["Biodiversité", "Développement solidaire", "Agroécologie"],
    url: "https://www.fondationensemble.org/",
    summary: "Biodiversité et développement solidaire dans les pays du Sud. Agroécologie, pêche durable, faune.",
    maxAmount: 150000,
  },
  {
    name: "Fondation Iris",
    themes: ["Environnement", "Transition", "Innovation"],
    url: "https://www.fondation-iris.org/",
    summary: "Soutien aux projets environnementaux et de transition écologique. Sous égide de la Fondation de France.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Lemarchand",
    themes: ["Environnement", "Écologie", "Éducation"],
    url: "https://www.fondationlemarchand.org/",
    summary: "Protection de l'environnement et sensibilisation écologique.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Prince Albert II de Monaco",
    themes: ["Environnement", "Biodiversité", "Climat", "Océan"],
    url: "https://www.fpa2.org/",
    summary: "Environnement : climat, biodiversité, eau et océan. Active en France et à l'international.",
    maxAmount: 100000,
  },
  {
    name: "Fondation pour la Recherche sur la Biodiversité",
    themes: ["Biodiversité", "Recherche", "Nature"],
    url: "https://www.fondationbiodiversite.fr/",
    summary: "Appels à projets recherche sur la biodiversité.",
    maxAmount: 80000,
  },

  // ─── CULTURE / PATRIMOINE / ARTS ──────────────────────────────────
  {
    name: "Fondation Daniel Iffla-Osiris",
    themes: ["Culture", "Patrimoine", "Solidarité juive"],
    url: "https://www.fondationdaniel-osiris.com/",
    summary: "Patrimoine juif, culture, solidarité. Fondation RUP historique.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Martell",
    themes: ["Culture", "Territoires", "Architecture"],
    url: "https://www.fondationdentreprisemartell.com/",
    summary: "Art, architecture, innovation à Cognac. Résidences et expositions.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Notre Dame",
    themes: ["Culture", "Patrimoine religieux", "Solidarité"],
    url: "https://www.fondationnotredame.fr/",
    summary: "Patrimoine religieux, éducation, solidarité, média. Principale fondation catholique de Paris.",
    maxAmount: 60000,
  },
  {
    name: "Fondation du Judaïsme Français",
    themes: ["Culture", "Patrimoine", "Mémoire"],
    url: "https://www.fondationjudaisme.org/",
    summary: "Culture et patrimoine juifs, mémoire de la Shoah, lutte contre l'antisémitisme.",
    maxAmount: 40000,
  },

  // ─── ENFANCE / JEUNESSE / ÉDUCATION ───────────────────────────────
  {
    name: "Fondation Enfance",
    themes: ["Enfance", "Protection", "Droits de l'enfant"],
    url: "https://www.fondationenfance.org/",
    summary: "Protection et droits de l'enfant. Appels à projets annuels + plaidoyer.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Enfance et Partage",
    themes: ["Enfance", "Protection", "Maltraitance"],
    url: "https://www.enfance-et-partage.org/",
    summary: "Lutte contre la maltraitance des enfants. Accompagnement juridique et psychologique.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Air France",
    themes: ["Enfance", "Jeunesse", "Éducation", "Insertion"],
    url: "https://corporate.airfrance.com/fr/la-fondation-air-france",
    summary: "Enfance en difficulté et jeunesse en insertion. Projets en France et à l'international.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Raja-Danièle Marcovici",
    themes: ["Femmes", "Droits", "International"],
    url: "https://www.fondation-raja-marcovici.com/nos-appels-a-projets/",
    summary: "Promotion de la condition féminine en France et dans le monde. Projets portés par des associations.",
    maxAmount: 50000,
  },
  {
    name: "Fondation ELA",
    themes: ["Leucodystrophies", "Maladies génétiques", "Enfance"],
    url: "https://ela-asso.com/",
    summary: "Lutte contre les leucodystrophies. Recherche, familles, sensibilisation en milieu scolaire.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Un Avenir Ensemble",
    themes: ["Jeunesse", "Mérite", "Bourses"],
    url: "https://www.legiondhonneur.fr/fr/page/un-avenir-ensemble/21",
    summary: "Bourses et parrainage pour jeunes boursiers méritants par la Grande Chancellerie de la Légion d'honneur.",
    maxAmount: 10000,
  },
  {
    name: "Fondation Action Enfance",
    themes: ["Protection de l'enfance", "Hébergement", "Jeunesse"],
    url: "https://www.actionenfance.org/",
    summary: "Protection de l'enfance : villages d'enfants, accompagnement des fratries séparées.",
    maxAmount: 50000,
  },

  // ─── SOLIDARITÉ INTERNATIONALE / HUMANITAIRE ──────────────────────
  {
    name: "Fondation Action contre la Faim",
    themes: ["Humanitaire", "Nutrition", "Urgence"],
    url: "https://www.actioncontrelafaim.org/",
    summary: "Lutte contre la faim et la malnutrition dans 55 pays. Opérations d'urgence et programmes long terme.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Danielle Mitterrand — France Libertés",
    themes: ["Droits humains", "Eau", "Peuples autochtones"],
    url: "https://www.france-libertes.org/",
    summary: "Défense des droits humains, accès à l'eau, peuples autochtones.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Un monde par tous",
    themes: ["Droits humains", "Solidarité internationale"],
    url: "https://www.fondation-un-monde-par-tous.org/",
    summary: "Justice sociale et économique, droits humains, solidarité internationale.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Gilles Caron",
    themes: ["Photojournalisme", "Médias", "Droits humains"],
    url: "https://fondationgillescaron.org/",
    summary: "Photojournalisme d'investigation et défense du droit à l'information.",
    maxAmount: 15000,
  },

  // ─── FEMMES / ÉGALITÉ ─────────────────────────────────────────────
  {
    name: "Fondation ELLE",
    themes: ["Femmes", "Égalité", "Éducation"],
    url: "https://www.fondation-elle.org/",
    summary: "Éducation des femmes et lutte contre les violences. Bourses et soutien aux associations terrain.",
    maxAmount: 30000,
  },

  // ─── MAISONS / GRANDES FAMILLES ───────────────────────────────────
  {
    name: "Fondation Rothschild",
    themes: ["Santé", "Recherche", "Culture"],
    url: "https://www.fondation-rothschild.fr/",
    summary: "Hôpital Rothschild, recherche médicale, culture et solidarité.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Martine Aublet",
    themes: ["Anthropologie", "Recherche", "Études doctorales"],
    url: "https://www.fondation-martine-aublet.org/",
    summary: "Bourses doctorales en anthropologie, archéologie, muséographie. Partenariat musée du Quai Branly.",
    maxAmount: 25000,
  },

  // ─── AJOUTS 2026-04 — ÉLARGISSEMENT EXHAUSTIVITÉ ──────────────────
  // Nouvelles fondations françaises d'intérêt général finançant des
  // associations/projets. Ordre : par thématique/secteur.

  // ─── GÉNÉRALISTES / INSTITUT DE FRANCE ────────────────────────────
  {
    name: "Fondation Simone et Cino Del Duca",
    themes: ["Culture", "Recherche", "Solidarité", "Archéologie"],
    url: "https://www.institutdefrance.fr/la-fondation-simone-et-cino-del-duca/",
    summary: "Fondation abritée par l'Institut de France. Prix et subventions en sciences, lettres, arts, archéologie. Action sociale aussi.",
    maxAmount: 200000,
  },
  {
    name: "Fondation Dassault",
    themes: ["Patrimoine", "Culture", "Solidarité"],
    url: "https://www.fondationdassault.fr/",
    summary: "Fondation abritée à l'Institut de France. Prix et mécénat patrimoine, culture, solidarité.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Marcel Bleustein-Blanchet pour la Vocation",
    themes: ["Jeunesse", "Vocation", "Bourses"],
    url: "https://www.fondationvocation.org/",
    summary: "Bourses de la Vocation pour jeunes 18-30 ans ayant un projet professionnel artistique, artisanal, scientifique ou humanitaire.",
    maxAmount: 8000,
  },
  {
    name: "Fondation Charles Léopold Mayer pour le Progrès de l'Homme",
    themes: ["Démocratie", "Écologie", "Gouvernance", "Solidarité internationale"],
    url: "https://www.fph.ch/",
    summary: "Fondation franco-suisse. Soutient des projets de transformation démocratique, écologique et sociale. Appels à projets ciblés.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Agir Contre l'Exclusion (FACE)",
    themes: ["Exclusion", "Emploi", "Inclusion", "Précarité"],
    url: "https://www.fondationface.org/",
    summary: "Fondation d'entreprise multi-partenariale luttant contre l'exclusion via l'emploi, l'éducation, l'inclusion numérique.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Terre Plurielle (Bouygues Construction)",
    themes: ["Solidarité", "Santé", "Éducation", "Insertion"],
    url: "https://www.bouygues-construction.com/fondation-terre-plurielle",
    summary: "Fondation Bouygues Construction : santé, éducation, insertion. Projets en France et dans les pays où le groupe opère.",
    maxAmount: 30000,
  },

  // ─── ENTREPRISE — INDUSTRIE / ÉNERGIE (compléments) ───────────────
  {
    name: "Fondation ArcelorMittal",
    themes: ["Éducation", "Insertion", "Santé", "Environnement"],
    url: "https://france.arcelormittal.com/en/Responsabilite/Fondation-ArcelorMittal-France",
    summary: "Fondation de l'aciériste. Éducation, insertion, santé, environnement. Projets sur les territoires d'implantation.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Saint-Gobain Initiatives",
    themes: ["Insertion", "Logement", "Éducation", "Solidarité"],
    url: "https://www.saint-gobain.com/fr/fondation",
    summary: "Fondation d'entreprise Saint-Gobain. Insertion professionnelle, habitat des plus démunis, éducation.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Solvay",
    themes: ["Science", "Recherche", "Éducation"],
    url: "https://www.solvay.com/en/sustainability/solvay-fund",
    summary: "Fondation du groupe chimique. Soutien à la recherche scientifique, l'enseignement et l'innovation durable.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Bosch France",
    themes: ["Éducation", "Numérique", "Insertion"],
    url: "https://www.bosch.fr/notre-entreprise/engagement-societal/",
    summary: "Engagement sociétal Bosch France. Programmes d'éducation technique, formation, insertion jeunes.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Bolloré",
    themes: ["Éducation", "Culture", "Solidarité", "Afrique"],
    url: "https://www.bollore.com/fr/engagements-du-groupe/mecenat-et-fondation-bollore/",
    summary: "Mécénat Bolloré : culture, éducation, solidarité. Projets Afrique et France. Nombreux partenariats culturels.",
    maxAmount: 50000,
  },

  // ─── ENTREPRISE — BANQUE / ASSURANCE (compléments) ────────────────
  {
    name: "Fondation CIC",
    themes: ["Solidarité", "Culture", "Sport", "Patrimoine"],
    url: "https://www.cic.fr/fr/banques/institutionnel/fondation-cic/index.html",
    summary: "Fondation du CIC. Soutien à la musique, au patrimoine et aux projets solidaires territoriaux.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Crédit Mutuel Alliance Fédérale",
    themes: ["Lecture", "Solidarité", "Éducation", "Écrit"],
    url: "https://www.creditmutuelalliancefederale.fr/fr/fondation-credit-mutuel.html",
    summary: "Fondation du Crédit Mutuel. Engagement historique pour la lecture, l'écriture et l'éducation. Prix littéraires, appels à projets.",
    maxAmount: 50000,
  },
  {
    name: "Fondation HSBC pour l'Éducation",
    themes: ["Éducation", "Jeunesse", "Réussite scolaire"],
    url: "https://www.hsbc.fr/1/2/hsbc-france/a-propos/fondation-hsbc",
    summary: "Fondation HSBC France : programmes éducatifs pour jeunes éloignés de la réussite scolaire.",
    maxAmount: 30000,
  },
  {
    name: "Fondation La Banque Postale",
    themes: ["Musique", "Solidarité", "Culture", "Accès"],
    url: "https://www.labanquepostale.com/fondation.html",
    summary: "Fondation La Banque Postale : accès à la musique classique, insertion par la culture, éducation musicale.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Natixis",
    themes: ["Solidarité", "Éducation", "Insertion"],
    url: "https://www.natixis.com/natixis/jcms/lpaz5_98404/fr/fondation-natixis",
    summary: "Fondation Natixis. Engagement sociétal : éducation, insertion professionnelle, actions solidaires.",
    maxAmount: 30000,
  },
  {
    name: "Fondation GMF",
    themes: ["Handicap", "Accessibilité", "Santé"],
    url: "https://www.gmf.fr/la-gmf/fondation",
    summary: "Fondation GMF : accès aux soins et à la culture pour les personnes handicapées. Appels à projets handicap.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Matmut",
    themes: ["Art", "Culture", "Solidarité"],
    url: "https://www.fondation-matmut.fr/",
    summary: "Fondation Matmut pour les Arts. Expositions, résidences, soutien aux artistes contemporains.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Covéa",
    themes: ["Solidarité", "Prévention", "Santé"],
    url: "https://www.covea.com/notre-engagement-societal/fondation-covea",
    summary: "Fondation Covéa (MMA, MAAF, GMF). Prévention des risques, solidarité, accompagnement des victimes.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Harmonie Mutuelle",
    themes: ["Santé", "Prévention", "Solidarité"],
    url: "https://www.harmonie-mutuelle.fr/la-mutuelle/nos-engagements/fondation-harmonie-mutuelle",
    summary: "Fondation d'entreprise Harmonie Mutuelle. Prévention santé, soutien aux aidants, inclusion.",
    maxAmount: 25000,
  },

  // ─── ENTREPRISE — DISTRIBUTION / ALIMENTATION (compléments) ───────
  {
    name: "Fondation Sodexo Stop Hunger",
    themes: ["Alimentation", "Précarité", "Femmes", "Insertion"],
    url: "https://stop-hunger.org/",
    summary: "Fondation Sodexo Stop Hunger. Lutte contre la faim, accès à une alimentation durable, autonomisation des femmes.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Système U",
    themes: ["Jeunesse", "Insertion", "Handicap", "Solidarité locale"],
    url: "https://www.magasins-u.com/fondation-systeme-u",
    summary: "Fondation coopérative Système U. Projets jeunesse, handicap, insertion soutenus via les magasins U.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Mars France",
    themes: ["Nutrition", "Bien-être animal", "Alimentation"],
    url: "https://www.mars.com/france/notre-engagement",
    summary: "Engagement Mars France. Nutrition, bien-être animal, alimentation durable. Partenariats associatifs.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Pierre Frachon (Intermarché-Les Mousquetaires)",
    themes: ["Solidarité", "Insertion", "Famille"],
    url: "https://www.mousquetaires.com/fondation/",
    summary: "Fondation du groupement Les Mousquetaires. Projets solidaires, familles, insertion.",
    maxAmount: 20000,
  },

  // ─── ENTREPRISE — LUXE / MODE / COSMÉTIQUE (compléments) ──────────
  {
    name: "Fondation Yves Saint Laurent",
    themes: ["Art", "Patrimoine", "Culture"],
    url: "https://museeyslparis.com/fondation",
    summary: "Fondation Pierre Bergé - Yves Saint Laurent. Musée YSL Paris, patrimoine mode, expositions.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Dior",
    themes: ["Art", "Mode", "Patrimoine", "Jeunes talents"],
    url: "https://www.dior.com/fr_fr/fashion/lexique-de-la-mode/christian-dior",
    summary: "Mécénat Dior. Soutien aux jeunes créateurs, art contemporain, danse, musées.",
    maxAmount: 50000,
  },
  {
    name: "Fondation d'entreprise Clarins",
    themes: ["Enfance", "Santé", "Femmes"],
    url: "https://www.groupeclarins.com/fr/la-fondation/",
    summary: "Fondation Clarins. Aide à l'enfance, santé des mères et des nouveau-nés. Partenariats ONG.",
    maxAmount: 30000,
  },
  {
    name: "Fondation d'entreprise Pernod Ricard",
    themes: ["Art", "Culture", "Jeunes artistes"],
    url: "https://www.fondation-pernod-ricard.com/",
    summary: "Fondation Pernod Ricard. Scène artistique émergente, prix Pernod Ricard, expositions d'art contemporain.",
    maxAmount: 50000,
  },
  {
    name: "Fondation LUMA Arles",
    themes: ["Art contemporain", "Culture", "Environnement"],
    url: "https://www.luma.org/",
    summary: "Fondation LUMA (Maja Hoffmann). Art contemporain, environnement, droits humains. Campus LUMA à Arles.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Fiminco",
    themes: ["Art contemporain", "Résidences", "Jeunes artistes"],
    url: "https://fondationfiminco.com/",
    summary: "Fondation Fiminco. Résidences d'artistes, expositions, soutien aux jeunes plasticiens à Romainville.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Custodia",
    themes: ["Art", "Patrimoine", "Dessins anciens"],
    url: "https://www.fondationcustodia.fr/",
    summary: "Fondation Custodia. Collection Frits Lugt. Expositions, recherche, publications sur le dessin ancien.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Vasarely",
    themes: ["Art", "Patrimoine", "Éducation artistique"],
    url: "https://www.fondationvasarely.org/",
    summary: "Fondation Vasarely à Aix-en-Provence. Centre architectonique, expositions, médiation art optique.",
    maxAmount: 20000,
  },

  // ─── ENTREPRISE — TECH / NUMÉRIQUE (compléments) ──────────────────
  {
    name: "Fondation Free",
    themes: ["Numérique", "Inclusion", "Éducation"],
    url: "https://www.free.fr/freebox/",
    summary: "Engagement Iliad-Free : inclusion numérique, éducation au code, lutte contre la fracture numérique.",
    maxAmount: 25000,
  },
  {
    name: "Fondation SFR",
    themes: ["Jeunesse", "Numérique", "Culture"],
    url: "https://www.sfr.com/fondation-sfr.html",
    summary: "Fondation SFR. Insertion professionnelle des jeunes, médiation numérique, culture.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Salesforce France",
    themes: ["Numérique", "Éducation", "Égalité"],
    url: "https://www.salesforce.com/fr/foundation/",
    summary: "Salesforce Foundation France. Modèle 1-1-1 : dons financiers, bénévolat, produits à tarif réduit aux associations.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Google.org France",
    themes: ["Numérique", "Innovation sociale", "Éducation"],
    url: "https://www.google.org/",
    summary: "Google.org engagement France. Subventions IA for social good, inclusion numérique, éducation.",
    maxAmount: 100000,
  },
  {
    name: "Fondation Capgemini",
    themes: ["Éducation", "Numérique", "Inclusion"],
    url: "https://www.capgemini.com/fr-fr/news/inside-stories/fondation-capgemini/",
    summary: "Fondation Capgemini. Accès à l'éducation numérique, formation, insertion des publics éloignés.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Atos",
    themes: ["Numérique", "Éducation", "Environnement"],
    url: "https://atos.net/fr/la-fondation-atos",
    summary: "Fondation Atos (devenue Eviden) : éducation numérique, environnement, projets bénévolat salariés.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Sopra Steria-Institut de France",
    themes: ["Numérique", "Éducation", "Jeunesse"],
    url: "https://www.fondation-soprasteria-institutdefrance.org/",
    summary: "Fondation Sopra Steria abritée Institut de France. Insertion des jeunes par le numérique.",
    maxAmount: 40000,
  },

  // ─── SANTÉ / RECHERCHE MÉDICALE (compléments) ─────────────────────
  {
    name: "Fondation Paralysie Cérébrale (La Fondation Motrice)",
    themes: ["Santé", "Handicap", "Recherche"],
    url: "https://www.fondationparalysiecerebrale.org/",
    summary: "Fondation Paralysie Cérébrale. Recherche sur l'IMC, bourses, appels à projets scientifiques et médicaux.",
    maxAmount: 60000,
  },
  {
    name: "Fondation Vaincre Alzheimer",
    themes: ["Santé", "Alzheimer", "Recherche"],
    url: "https://www.vaincrealzheimer.org/",
    summary: "Fondation Vaincre Alzheimer (ex-LECMA). Financement de la recherche sur Alzheimer et maladies apparentées.",
    maxAmount: 100000,
  },
  {
    name: "Fondation pour l'Audition",
    themes: ["Santé", "Surdité", "Recherche", "Accessibilité"],
    url: "https://www.fondationpourlaudition.org/",
    summary: "Fondation pour l'Audition. Recherche, accompagnement, accessibilité auditive. Appels à projets recherche et associatifs.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Voir & Entendre",
    themes: ["Santé", "Vision", "Audition", "Recherche"],
    url: "https://voiretentendre.org/",
    summary: "Institut de la Vision / Fondation Voir & Entendre. Recherche ophtalmologique et auditive.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Jérôme Lejeune",
    themes: ["Santé", "Trisomie", "Handicap", "Recherche"],
    url: "https://www.fondationlejeune.org/",
    summary: "Fondation Jérôme Lejeune. Recherche, soin et défense des personnes trisomiques ou porteuses de maladies génétiques.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Groupe Pasteur Mutualité",
    themes: ["Santé", "Recherche", "Prévention"],
    url: "https://www.gpm.fr/fondation/",
    summary: "Fondation Groupe Pasteur Mutualité. Soutien recherche médicale, prévention, appels à projets santé publique.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Simone Veil",
    themes: ["Santé", "Femmes", "Droits"],
    url: "https://www.fondationsimoneveil.fr/",
    summary: "Fondation Simone Veil. Défense des droits des femmes, mémoire de la Shoah, santé.",
    maxAmount: 30000,
  },
  {
    name: "Fondation AP-HP pour la Recherche",
    themes: ["Santé", "Recherche", "Hôpital"],
    url: "https://fondationrechercheaphp.fr/",
    summary: "Fondation recherche Assistance Publique - Hôpitaux de Paris. Finance la recherche clinique et translationnelle.",
    maxAmount: 50000,
  },

  // ─── HANDICAP / INCLUSION (compléments) ───────────────────────────
  {
    name: "Fondation Anne de Gaulle",
    themes: ["Handicap", "Inclusion", "Personnes vulnérables"],
    url: "https://www.fondationannedegaulle.org/",
    summary: "Fondation Anne de Gaulle. Accompagnement des personnes en situation de handicap mental. Établissements et projets associatifs.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Valentin Haüy",
    themes: ["Handicap", "Cécité", "Accessibilité"],
    url: "https://www.avh.asso.fr/",
    summary: "Association Valentin Haüy (fondation abritée). Accompagnement des déficients visuels, bibliothèque, emploi.",
    maxAmount: 25000,
  },
  {
    name: "Fondation John Bost",
    themes: ["Handicap", "Psychique", "Inclusion"],
    url: "https://www.johnbost.fr/fondation/",
    summary: "Fondation John Bost. Accueil et soin des personnes handicapées psychiques. 35 établissements.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Institut Le Bel Age",
    themes: ["Grand âge", "Aidants", "Santé"],
    url: "https://www.ocirp.fr/fondation-ocirp",
    summary: "Fondation OCIRP / Le Bel Âge. Accompagnement des aidants, orphelins, personnes dépendantes.",
    maxAmount: 40000,
  },
  {
    name: "Fondation de France — Programme Handicap",
    themes: ["Handicap", "Inclusion"],
    url: "https://www.fondationdefrance.org/fr/fondation/le-programme-handicap",
    summary: "Programme Handicap de la Fondation de France. Appels à projets pour l'inclusion des personnes handicapées.",
    maxAmount: 40000,
  },

  // ─── ENVIRONNEMENT / BIODIVERSITÉ / CLIMAT (compléments) ──────────
  {
    name: "Fondation WWF France",
    themes: ["Environnement", "Biodiversité", "Climat"],
    url: "https://www.wwf.fr/",
    summary: "WWF France (fondation reconnue d'utilité publique). Protection biodiversité, climat, océans. Partenariats associatifs.",
    maxAmount: 50000,
  },
  {
    name: "Fondation pour la Nature et l'Homme",
    themes: ["Environnement", "Éducation", "Transition"],
    url: "https://www.fnh.org/",
    summary: "Fondation pour la Nature et l'Homme (FNH). Transition écologique, éducation, plaidoyer.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Good Planet — Action Carbone Solidaire",
    themes: ["Environnement", "Climat", "Solidarité internationale"],
    url: "https://www.goodplanet.org/fr/action-carbone-solidaire/",
    summary: "Programme Action Carbone Solidaire. Finance des projets bas-carbone dans les pays du Sud.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Terre d'Aventure",
    themes: ["Environnement", "Voyage responsable", "Solidarité"],
    url: "https://www.terdav.com/",
    summary: "Fondation Terres d'Aventure. Projets environnementaux et solidaires dans les destinations du groupe.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Patagonia France",
    themes: ["Environnement", "Activisme", "Climat"],
    url: "https://eu.patagonia.com/fr/fr/environmentalism/",
    summary: "Programme environnemental Patagonia France. 1% For The Planet. Finance des associations activistes environnementales.",
    maxAmount: 30000,
  },
  {
    name: "Fondation pour la Recherche sur la Biodiversité (FRB)",
    themes: ["Biodiversité", "Recherche", "Environnement"],
    url: "https://www.fondationbiodiversite.fr/",
    summary: "FRB. Structure nationale pour la recherche sur la biodiversité. Appels à projets, mobilisation de la recherche.",
    maxAmount: 80000,
  },
  {
    name: "Fondation Norsys",
    themes: ["Environnement", "Numérique responsable"],
    url: "https://www.norsys.fr/fondation-norsys/",
    summary: "Fondation Norsys. Préservation de la biodiversité, numérique responsable, projets éducatifs.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Rainett",
    themes: ["Environnement", "Éducation", "Biodiversité"],
    url: "https://www.rainett.fr/engagements/",
    summary: "Fonds Rainett (Werner & Mertz). Soutien aux associations pour la biodiversité et l'éducation à l'environnement.",
    maxAmount: 15000,
  },

  // ─── CULTURE / PATRIMOINE / ARTS (compléments) ────────────────────
  {
    name: "Fondation Calouste Gulbenkian — Délégation France",
    themes: ["Culture", "Art", "Sciences", "Éducation"],
    url: "https://gulbenkian.pt/paris/",
    summary: "Délégation française de la Fondation Calouste Gulbenkian. Projets culturels et scientifiques, bourses.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Boghossian — Villa Empain",
    themes: ["Art", "Dialogue", "Orient-Occident"],
    url: "https://www.villaempain.com/",
    summary: "Fondation Boghossian. Dialogue des cultures Orient-Occident via l'art à la Villa Empain.",
    maxAmount: 30000,
  },
  {
    name: "Fondation d'entreprise Ricard",
    themes: ["Art contemporain", "Jeunes artistes"],
    url: "https://www.fondation-entreprise-ricard.com/",
    summary: "Espace de la Fondation d'entreprise Ricard. Prix Fondation Ricard, exposition de la jeune scène artistique.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Gandur pour l'Art",
    themes: ["Art", "Collection", "Culture"],
    url: "https://fg-art.org/",
    summary: "Fondation Gandur pour l'Art. Collection encyclopédique, prêts à des institutions françaises, soutien expositions.",
    maxAmount: 40000,
  },
  {
    name: "Fondation Jan Michalski pour l'Écriture et la Littérature",
    themes: ["Littérature", "Résidences", "Écriture"],
    url: "https://www.fondation-janmichalski.com/",
    summary: "Fondation Jan Michalski. Résidences d'écrivains, prix littéraire, bibliothèque (Montricher, CH).",
    maxAmount: 25000,
  },

  // ─── ENFANCE / JEUNESSE / ÉDUCATION (compléments) ─────────────────
  {
    name: "Fondation Aide et Action",
    themes: ["Éducation", "Solidarité internationale", "Jeunesse"],
    url: "https://www.aide-et-action.org/",
    summary: "Aide et Action (fondation reconnue d'utilité publique). Accès à l'éducation dans 25 pays.",
    maxAmount: 40000,
  },
  {
    name: "Fondation EY France",
    themes: ["Insertion", "Jeunesse", "Entrepreneuriat"],
    url: "https://www.ey.com/fr_fr/corporate-responsibility/fondation-ey",
    summary: "Fondation EY France. Accompagnement entrepreneurial des jeunes éloignés de l'emploi.",
    maxAmount: 25000,
  },
  {
    name: "Fondation KPMG France",
    themes: ["Éducation", "Insertion", "Diversité"],
    url: "https://kpmg.com/fr/fr/home/about/fondation-kpmg-france.html",
    summary: "Fondation KPMG France. Accès à l'éducation et à l'emploi des jeunes en difficulté.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Deloitte France",
    themes: ["Insertion", "Éducation", "Inclusion"],
    url: "https://www2.deloitte.com/fr/fr/pages/about-deloitte/articles/la-fondation-deloitte.html",
    summary: "Fondation Deloitte France. Insertion des jeunes, inclusion sociale, projets éducatifs.",
    maxAmount: 25000,
  },
  {
    name: "Fondation PwC France",
    themes: ["Éducation", "Égalité", "Insertion"],
    url: "https://www.pwc.fr/fr/qui-sommes-nous/responsabilite-entreprise/fondation-pwc.html",
    summary: "Fondation PwC France. Égalité des chances, éducation, insertion des jeunes.",
    maxAmount: 20000,
  },
  {
    name: "Fondation SPIE",
    themes: ["Insertion", "Jeunesse", "Formation"],
    url: "https://www.spie.com/fr/fondation-spie",
    summary: "Fondation SPIE. Insertion des jeunes éloignés de l'emploi, formation professionnelle.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Môm'artre",
    themes: ["Enfance", "Art", "Accompagnement"],
    url: "https://www.momartre.com/",
    summary: "Réseau Môm'artre / fondation. Accueil des enfants 4-14 ans après l'école par des artistes.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Break Poverty",
    themes: ["Précarité", "Jeunesse", "Éducation"],
    url: "https://www.breakpoverty.com/",
    summary: "Fondation Break Poverty. Coalitions territoriales contre la pauvreté des enfants et des jeunes.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Un avenir avec l'Armée du Salut",
    themes: ["Précarité", "Exclusion", "Solidarité"],
    url: "https://www.armeedusalut.fr/",
    summary: "Fondation de l'Armée du Salut. Hébergement d'urgence, insertion, lutte contre l'exclusion.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Père Brottier",
    themes: ["Éducation", "Jeunesse", "Insertion"],
    url: "https://www.fondation-perebrottier.org/",
    summary: "Fondation Père Brottier (congrégation Saint-Esprit). Éducation et insertion des jeunes défavorisés.",
    maxAmount: 15000,
  },

  // ─── SOLIDARITÉ INTERNATIONALE / HUMANITAIRE (compléments) ────────
  {
    name: "Fondation Secours Islamique France",
    themes: ["Humanitaire", "Urgence", "Développement"],
    url: "https://www.secours-islamique.org/",
    summary: "Secours Islamique France (RUP). Urgences humanitaires, sécurité alimentaire, accès à l'eau.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Humanité et Inclusion (Handicap International)",
    themes: ["Handicap", "Humanitaire", "Développement"],
    url: "https://www.hi.org/fr/",
    summary: "Humanité et Inclusion (Handicap International France). Projets handicap dans 60+ pays.",
    maxAmount: 50000,
  },
  {
    name: "Fondation Plan International France",
    themes: ["Enfance", "Droits des filles", "Solidarité internationale"],
    url: "https://www.plan-international.fr/",
    summary: "Plan International France. Défense des droits des filles et des enfants dans le monde.",
    maxAmount: 40000,
  },
  {
    name: "Fondation CARE France",
    themes: ["Humanitaire", "Femmes", "Développement"],
    url: "https://www.carefrance.org/",
    summary: "CARE France. Lutte contre la pauvreté, autonomisation des femmes, urgences humanitaires.",
    maxAmount: 50000,
  },

  // ─── FEMMES / ÉGALITÉ (compléments) ───────────────────────────────
  {
    name: "Fondation des Femmes",
    themes: ["Femmes", "Violences", "Droits"],
    url: "https://fondationdesfemmes.org/",
    summary: "Fondation des Femmes. Droits des femmes, lutte contre les violences sexistes. Appels à projets associations féministes.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Marie Claire — Prix de la Solidarité",
    themes: ["Femmes", "Solidarité", "Éducation"],
    url: "https://www.marieclaire.fr/,prix-de-la-solidarite,",
    summary: "Prix de la Solidarité Marie Claire. Projets pour les femmes dans le monde. Dotation annuelle.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Egalité Mixité — Agir pour l'Égalité",
    themes: ["Égalité", "Mixité", "Femmes"],
    url: "https://www.fondation-egalitemixite.org/",
    summary: "Fondation Égalité Mixité (Face + partenaires). Mixité professionnelle, égalité femmes-hommes.",
    maxAmount: 20000,
  },

  // ─── MÉDIAS / DÉMOCRATIE / THINK TANKS ────────────────────────────
  {
    name: "Fondation Jean-Jaurès",
    themes: ["Démocratie", "Politique", "Recherche"],
    url: "https://www.jean-jaures.org/",
    summary: "Fondation Jean-Jaurès. Think tank progressiste. Notes, débats, bourses de recherche, Université d'été.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Robert Schuman",
    themes: ["Europe", "Démocratie", "Recherche"],
    url: "https://www.robert-schuman.eu/",
    summary: "Fondation Robert Schuman. Recherche européenne, publications, bourses doctorales sur l'Europe.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Copernic",
    themes: ["Démocratie", "Recherche critique", "Solidarité"],
    url: "https://www.fondation-copernic.org/",
    summary: "Fondation Copernic. Think tank critique, analyses politiques et sociales.",
    maxAmount: 10000,
  },
  {
    name: "Fondation Terra Nova",
    themes: ["Politique", "Social", "Écologie"],
    url: "https://tnova.fr/",
    summary: "Fondation Terra Nova. Think tank progressiste, production d'idées, notes et propositions.",
    maxAmount: 15000,
  },
  {
    name: "Fondation pour l'Innovation Politique (Fondapol)",
    themes: ["Politique", "Libéralisme", "Recherche"],
    url: "https://www.fondapol.org/",
    summary: "Fondapol. Think tank libéral, progressiste, européen. Publications, sondages, notes politiques.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Hirondelle — Médias et Démocratie",
    themes: ["Médias", "Démocratie", "Solidarité internationale"],
    url: "https://www.hirondelle.org/fr/",
    summary: "Fondation Hirondelle (déjà présente sous autre forme). Médias d'information en zones de crise.",
    maxAmount: 40000,
  },
  {
    name: "Institut Montaigne",
    themes: ["Politique", "Économie", "Recherche"],
    url: "https://www.institutmontaigne.org/",
    summary: "Institut Montaigne. Think tank indépendant, études et propositions de politiques publiques.",
    maxAmount: 15000,
  },
  {
    name: "Fondation de l'Écologie Politique",
    themes: ["Écologie", "Démocratie", "Recherche"],
    url: "https://fondationecolo.org/",
    summary: "Fondation de l'Écologie Politique. Think tank écologiste, publications et débats.",
    maxAmount: 10000,
  },

  // ─── FONDATIONS TERRITORIALES / ABRITANTES ────────────────────────
  {
    name: "Fondation de Lille",
    themes: ["Territoires", "Solidarité", "Culture"],
    url: "https://www.fondationdelille.org/",
    summary: "Fondation de Lille. Fondation territoriale abritante. Appels à projets territoire lillois, solidarité, culture.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Université de Strasbourg",
    themes: ["Recherche", "Enseignement supérieur", "Innovation"],
    url: "https://fondation.unistra.fr/",
    summary: "Fondation Université de Strasbourg. Soutient recherche, formation, vie étudiante, international.",
    maxAmount: 30000,
  },
  {
    name: "Fondation Bordeaux Université",
    themes: ["Recherche", "Enseignement", "Jeunesse"],
    url: "https://www.fondation.univ-bordeaux.fr/",
    summary: "Fondation Bordeaux Université. Projets de recherche, bourses, rayonnement.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Alsace",
    themes: ["Territoires", "Culture", "Solidarité"],
    url: "https://www.fondation-alsace.org/",
    summary: "Fondation Alsace. Fondation territoriale abritante. Appels à projets alsaciens variés.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Bullukian",
    themes: ["Art", "Culture", "Arménie"],
    url: "https://www.bullukian.com/",
    summary: "Fondation Bullukian (Lyon). Art contemporain, mémoire arménienne, expositions et prix.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Normandie Université",
    themes: ["Recherche", "Territoires", "Éducation"],
    url: "https://fondation.normandie-univ.fr/",
    summary: "Fondation Normandie Université. Recherche, formation, attractivité du territoire.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Grenoble INP",
    themes: ["Recherche", "Ingénierie", "Innovation"],
    url: "https://fondation.grenoble-inp.fr/",
    summary: "Fondation Grenoble INP. Soutien à l'ingénierie, la recherche et la formation technologique.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Vallée du Rhône",
    themes: ["Territoires", "Solidarité", "Culture"],
    url: "https://www.fondationvalleedurhone.org/",
    summary: "Fondation territoriale Vallée du Rhône. Projets solidaires et culturels locaux.",
    maxAmount: 10000,
  },

  // ─── ANIMAUX / BIEN-ÊTRE ANIMAL ───────────────────────────────────
  {
    name: "Fondation 30 Millions d'Amis",
    themes: ["Animaux", "Bien-être animal", "Protection"],
    url: "https://www.30millionsdamis.fr/fondation/",
    summary: "Fondation 30 Millions d'Amis. Protection animale, refuges, stérilisation, lutte contre l'abandon.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Brigitte Bardot",
    themes: ["Animaux", "Protection animale"],
    url: "https://www.fondationbrigittebardot.fr/",
    summary: "Fondation Brigitte Bardot. Protection des animaux domestiques et sauvages, refuges, enquêtes.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Assistance aux Animaux",
    themes: ["Animaux", "Refuges"],
    url: "https://www.fondationassistanceauxanimaux.org/",
    summary: "Fondation Assistance aux Animaux. Refuges, dispensaires, défense animale.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Droit Animal",
    themes: ["Animaux", "Droit", "Plaidoyer"],
    url: "https://www.fondation-droit-animal.org/",
    summary: "LFDA - Fondation Droit Animal, Éthique et Sciences. Recherche juridique et plaidoyer pour les animaux.",
    maxAmount: 10000,
  },
  {
    name: "Fondation Clara",
    themes: ["Animaux", "Refuges", "Chiens"],
    url: "https://www.fondationclara.com/",
    summary: "Fondation Clara. Protection des animaux abandonnés, soutien aux refuges en France.",
    maxAmount: 10000,
  },
  {
    name: "Fondation Un Cœur",
    themes: ["Animaux", "Chiens de travail"],
    url: "https://www.fondationuncoeur.org/",
    summary: "Fondation Un Cœur. Soutien aux chiens d'assistance, chiens policiers et militaires, refuges.",
    maxAmount: 10000,
  },

  // ─── FONDATIONS RELIGIEUSES / COMMUNAUTAIRES (compléments) ────────
  {
    name: "Fondation du Protestantisme",
    themes: ["Solidarité", "Éducation", "Culture"],
    url: "https://www.fondationduprotestantisme.org/",
    summary: "Fondation du Protestantisme. Fondation abritante. Solidarité, culture, éducation, diaconie.",
    maxAmount: 20000,
  },
  {
    name: "Fondation de l'Islam de France",
    themes: ["Culture", "Éducation", "Citoyenneté"],
    url: "https://www.fondationislamdefrance.fr/",
    summary: "Fondation de l'Islam de France. Promotion d'un islam de France, culture, éducation, citoyenneté.",
    maxAmount: 25000,
  },
  {
    name: "Fondation Saint-Matthieu pour l'École Catholique",
    themes: ["Éducation", "Enseignement catholique"],
    url: "https://www.fondation-st-matthieu.org/",
    summary: "Fondation Saint-Matthieu. Soutien à l'enseignement catholique, bourses, rénovation.",
    maxAmount: 30000,
  },

  // ─── SPORT / INCLUSION (nouveau)───────────────────────────────────
  {
    name: "Fondation du Sport Français",
    themes: ["Sport", "Jeunesse", "Solidarité"],
    url: "https://www.fondationdusportfrancais.fr/",
    summary: "Fondation du Sport Français. Valeurs du sport, insertion, éducation, sport-santé.",
    maxAmount: 20000,
  },
  {
    name: "Fondation Alice Milliat",
    themes: ["Sport", "Femmes", "Égalité"],
    url: "https://alicemilliat.com/",
    summary: "Fondation Alice Milliat. Promotion du sport féminin, visibilité des sportives.",
    maxAmount: 15000,
  },
  {
    name: "Fondation Paris 2024 (héritage)",
    themes: ["Sport", "Inclusion", "Jeunesse"],
    url: "https://www.paris2024.org/fr/fonds-de-dotation/",
    summary: "Fonds de dotation Paris 2024. Héritage des Jeux : sport pour tous, inclusion, jeunesse.",
    maxAmount: 40000,
  },
  {
    name: "Fondation FDJ — Sport & Société",
    themes: ["Sport", "Insertion", "Jeunesse"],
    url: "https://www.groupefdj.com/fondation.html",
    summary: "Fondation FDJ (additionnelle). Sport et société, égalité des chances, insertion par le sport.",
    maxAmount: 25000,
  },
];

/**
 * Get all curated foundations as raw data (deduplicated by URL just in case).
 */
export function fetchCuratedFoundations() {
  const seen = new Set<string>();
  const unique = FONDATIONS.filter((f) => {
    if (seen.has(f.url)) return false;
    seen.add(f.url);
    return true;
  });
  console.log(`[Fondations curatées] ${unique.length} fondations`);
  return unique;
}

/**
 * Transform curated foundation to grant schema.
 *
 * Source name is kept as "Fondations françaises (curated)" — the matching
 * page uses /fondation/i in the source_name as a heuristic to surface a
 * "Contacter la fondation" CTA.
 */
export function transformCuratedToGrant(f: CuratedFoundation) {
  return {
    sourceUrl: f.url,
    sourceName: "Fondations françaises (curated)",
    title: f.name,
    summary: f.summary,
    rawContent: f.summary,
    funder: f.name,
    country: "FR",
    thematicAreas: f.themes,
    eligibleEntities: ["association", "ong"],
    eligibleCountries: ["FR"],
    minAmountEur: 1000,
    maxAmountEur: f.maxAmount,
    coFinancingRequired: false,
    deadline: null,
    grantType: "fondation",
    language: "fr",
    status: "active",
    aiSummary: f.summary,
  };
}
